### ISSUE TITLE
SSR: await for "componentDidMount"

### ISSUE THREAD

**Issue by Anonyfox** [seagull-js/seagull#13]
For all pages, if this handler exists, await it on the server.
Context: this is the place where async data fetching happens ideally, so when the developer uses "await" inside this handler, do actually await for "componentDidMount" to finish, so there is a good SEO-friendly HTML rendered.

**Comment by Harper04** [comment]
done in seagull-js/cli https://github.com/seagull-js/seagull-cli/commit/8e92156e1b6f6c38e03b5cf8c2830fd7697af8e9
