### ISSUE TITLE
Error @bundeling seagull app

### ISSUE THREAD

**Issue by fdrews** [seagull-js/seagull#28]
Can`t find /dist/frontend/index.js

![screen shot 2018-03-26 at 10 24 21](https://user-images.githubusercontent.com/10455916/37894945-30690e8a-30e0-11e8-9c33-f9d02d79d7eb.png)

Possible workaround downgrade core version to 0.9.9

**Comment by Harper04** [comment]
.seagull is missing in path

**Comment by Harper04** [comment]
i think it got introduced here
https://github.com/seagull-js/seagull/commit/4fe658d9f4cf8f0e1fe66be1c31fe48b2b2ce87d
but it should use the .seagull path

**Comment by Harper04** [comment]
Please update to 
@seagull/core@0.10.4
and 
@seagull/cli@0.12.3

**Comment by fdrews** [comment]
Ty it works!
