### ISSUE TITLE
react-helmet types dependency

### ISSUE THREAD

**Issue by m0dh4x** [seagull-js/seagull#37]
I have an error with import react-helmet
<img width="1286" alt="screen shot 2018-12-19 at 15 00 08" src="https://user-images.githubusercontent.com/10455916/50224710-d41e9180-039e-11e9-9b8b-76e934b16a1f.png">

**Comment by Anonyfox** [comment]
please use the exposed helmet singleton from the pages module instead: 

```typescript
import { Helmet } from '@seagull/pages'
```
