### ISSUE TITLE
Secure API Routes

### ISSUE THREAD

**Issue by Aduril** [seagull-js/seagull#44]
How do we want to proceed rgarding security?
Currently we cannot use API keys because we would secure the webpages as well. Therefore, we would block our own infrastructure.

We could carry our own security flag through cloudfront annd check for it within the lambda. In the end most solutions tend to be a figleaf only. But what do you think about it?

**Comment by Harper04** [comment]
implemented naiv auth method (pre shared token).
Future enhancement like other methods (user/password/ jwt) or supporting an array of valid keys when needed
