### ISSUE TITLE
Frontend State Management

### ISSUE THREAD

**Issue by Anonyfox** [seagull-js/seagull#5]
Since the choice is currently ~~Inferno in react-compat mode~~ React, the ideal state management candidate seems to be MobX. Maybe even a bit simplified, lets see.

**Comment by Anonyfox** [comment]
Target solution: automatic loading of a toplevel folder called "stores" (or sth like that), which contains TS files with MobX default class exports.

**Comment by Anonyfox** [comment]
Done, must be documented still.

**Comment by Anonyfox** [comment]
This is now an RFC.

**Comment by Harper04** [comment]
Wishlist:
- immutable core state
- 100% (!) typesafe
- async actions without 'magic' syntax (mobx...)
- pure functions for state changes
- no complexity
- hydratable from state
- context api based
- computeds (possibly cached), chain
- state change events
- As a single class
- looks nice in jsx

- (performance)

**Comment by Harper04** [comment]
does not apply anymore
